name: Make PKGBUILD

on:
  push:
  pull_request:

jobs:
  pkgbuild-validate:
    runs-on: ubuntu-latest
    name: Build arch package
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare PKGBUILD
        run: |
          sed -i 's/sneedacity-git/sneedacity-bin/g' pkg/arch/sneedacity-git/PKGBUILD
          rm pkg/arch/sneedacity-git/.SRCINFO

      - name: Build sneedacity-bin
        id: makepkg
        uses: edlanglois/pkgbuild-action@v1
        with:
          pkgdir: 'pkg/arch/sneedacity-git'

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sneedacity-arch-pkg
          path: "${{ steps.makepkg.outputs.pkgfile0 }}"
